name: child workflow

on:
  push:
    branches:
      - main
      
jobs:  
  deploy-pr:
    name: pr_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: pr
    secrets: inherit
  deploy-dev-with-approval:
    needs: deploy-pr
    name: dev_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: dev
    secrets: inherit
