name: child workflow

on:
  push:
    branches:
      - main
      
jobs:
  reusable_workflow_job:
    name: dev_echo
    uses: ./.github/workflows/base.yml
    with:
      environment: dev
    secrets: inherit
